// Code generated by github.com/actgardner/gogen-avro/v8. DO NOT EDIT.
/*
 * SOURCES:
 *     DateTime.avsc
 *     EventHeader.avsc
 *     Rating.avsc
 *     RatingEvent.avsc
 *     Reason.avsc
 */
package post_order_ratings

import (
	"io"

	"github.com/actgardner/gogen-avro/v9/vm"
	"github.com/actgardner/gogen-avro/v9/vm/types"
)

func writeArrayReason(r []Reason, w io.Writer) error {
	err := vm.WriteLong(int64(len(r)), w)
	if err != nil || len(r) == 0 {
		return err
	}
	for _, e := range r {
		err = writeReason(e, w)
		if err != nil {
			return err
		}
	}
	return vm.WriteLong(0, w)
}

type ArrayReasonWrapper struct {
	Target *[]Reason
}

func (_ *ArrayReasonWrapper) SetBoolean(v bool)                { panic("Unsupported operation") }
func (_ *ArrayReasonWrapper) SetInt(v int32)                   { panic("Unsupported operation") }
func (_ *ArrayReasonWrapper) SetLong(v int64)                  { panic("Unsupported operation") }
func (_ *ArrayReasonWrapper) SetFloat(v float32)               { panic("Unsupported operation") }
func (_ *ArrayReasonWrapper) SetDouble(v float64)              { panic("Unsupported operation") }
func (_ *ArrayReasonWrapper) SetBytes(v []byte)                { panic("Unsupported operation") }
func (_ *ArrayReasonWrapper) SetString(v string)               { panic("Unsupported operation") }
func (_ *ArrayReasonWrapper) SetUnionElem(v int64)             { panic("Unsupported operation") }
func (_ *ArrayReasonWrapper) Get(i int) types.Field            { panic("Unsupported operation") }
func (_ *ArrayReasonWrapper) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *ArrayReasonWrapper) Finalize()                        {}
func (_ *ArrayReasonWrapper) SetDefault(i int)                 { panic("Unsupported operation") }
func (r *ArrayReasonWrapper) NullField(i int) {
	panic("Unsupported operation")
}

func (r *ArrayReasonWrapper) AppendArray() types.Field {
	var v Reason
	v = NewReason()

	*r.Target = append(*r.Target, v)
	return &types.Record{Target: &(*r.Target)[len(*r.Target)-1]}
}
